package ConsultaApp;


/**
* ConsultaApp/ConsultaMedicaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConsultaMedica.idl
* Saturday, April 19, 2025 7:49:40 PM CAT
*/

public interface ConsultaMedicaOperations 
{
  ConsultaApp.Consulta agendarConsulta (String pacienteId, String medicoId, String data, String hora, String especialidade);
  ConsultaApp.Consulta agendarConsultaComId (String consultaId, String pacienteId, String pacienteNome, String medicoId, String medicoNome, String data, String hora, String especialidade, String status);
  boolean cancelarConsulta (String consultaId);
  ConsultaApp.Consulta getConsulta (String consultaId);
  ConsultaApp.Consulta[] getConsultasPorPaciente (String pacienteId);
  ConsultaApp.Consulta[] getConsultasPorMedico (String medicoId);
  ConsultaApp.Consulta[] getConsultasPorData (String data);
  ConsultaApp.Medico[] getMedicosPorEspecialidade (String especialidade);
  ConsultaApp.Medico getMedico (String medicoId);
  ConsultaApp.Paciente getPaciente (String pacienteId);
  ConsultaApp.Paciente[] getPacientes ();
  ConsultaApp.Medico[] getMedicos ();
  ConsultaApp.Consulta atualizarConsulta (String consultaId, String status);
} // interface ConsultaMedicaOperations
