package ConsultaApp;


/**
* ConsultaApp/Consulta.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConsultaMedica.idl
* Saturday, April 19, 2025 7:49:40 PM CAT
*/

public final class Consulta implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public String pacienteNome = null;
  public String medicoNome = null;
  public String data = null;
  public String hora = null;
  public String status = null;

  // "AGENDADA", "CONCLUIDA", "CANCELADA"
  public String especialidade = null;
  public String observacoes = null;

  public Consulta ()
  {
  } // ctor

  public Consulta (String _id, String _pacienteNome, String _medicoNome, String _data, String _hora, String _status, String _especialidade, String _observacoes)
  {
    id = _id;
    pacienteNome = _pacienteNome;
    medicoNome = _medicoNome;
    data = _data;
    hora = _hora;
    status = _status;
    especialidade = _especialidade;
    observacoes = _observacoes;
  } // ctor

} // class Consulta
