package ConsultaApp;


/**
* ConsultaApp/ConsultaSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConsultaMedica.idl
* Saturday, April 19, 2025 7:49:40 PM CAT
*/

public final class ConsultaSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public ConsultaApp.Consulta value[] = null;

  public ConsultaSeqHolder ()
  {
  }

  public ConsultaSeqHolder (ConsultaApp.Consulta[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConsultaApp.ConsultaSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConsultaApp.ConsultaSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConsultaApp.ConsultaSeqHelper.type ();
  }

}
