package ConsultaApp;


/**
* ConsultaApp/ConsultaMedicaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConsultaMedica.idl
* Saturday, April 19, 2025 7:49:40 PM CAT
*/

abstract public class ConsultaMedicaHelper
{
  private static String  _id = "IDL:ConsultaApp/ConsultaMedica:1.0";

  public static void insert (org.omg.CORBA.Any a, ConsultaApp.ConsultaMedica that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ConsultaApp.ConsultaMedica extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ConsultaApp.ConsultaMedicaHelper.id (), "ConsultaMedica");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ConsultaApp.ConsultaMedica read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ConsultaMedicaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ConsultaApp.ConsultaMedica value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ConsultaApp.ConsultaMedica narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ConsultaApp.ConsultaMedica)
      return (ConsultaApp.ConsultaMedica)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ConsultaApp._ConsultaMedicaStub stub = new ConsultaApp._ConsultaMedicaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ConsultaApp.ConsultaMedica unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ConsultaApp.ConsultaMedica)
      return (ConsultaApp.ConsultaMedica)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ConsultaApp._ConsultaMedicaStub stub = new ConsultaApp._ConsultaMedicaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
