package ConsultaApp;


/**
* ConsultaApp/PacienteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConsultaMedica.idl
* Saturday, April 19, 2025 7:49:40 PM CAT
*/

abstract public class PacienteHelper
{
  private static String  _id = "IDL:ConsultaApp/Paciente:1.0";

  public static void insert (org.omg.CORBA.Any a, ConsultaApp.Paciente that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ConsultaApp.Paciente extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "nome",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "cpf",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "email",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "telefone",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "dataNascimento",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ConsultaApp.PacienteHelper.id (), "Paciente", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ConsultaApp.Paciente read (org.omg.CORBA.portable.InputStream istream)
  {
    ConsultaApp.Paciente value = new ConsultaApp.Paciente ();
    value.id = istream.read_string ();
    value.nome = istream.read_string ();
    value.cpf = istream.read_string ();
    value.email = istream.read_string ();
    value.telefone = istream.read_string ();
    value.dataNascimento = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ConsultaApp.Paciente value)
  {
    ostream.write_string (value.id);
    ostream.write_string (value.nome);
    ostream.write_string (value.cpf);
    ostream.write_string (value.email);
    ostream.write_string (value.telefone);
    ostream.write_string (value.dataNascimento);
  }

}
