package ConsultaApp;


/**
* ConsultaApp/PacienteSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConsultaMedica.idl
* Saturday, April 19, 2025 7:49:40 PM CAT
*/

abstract public class PacienteSeqHelper
{
  private static String  _id = "IDL:ConsultaApp/PacienteSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, ConsultaApp.Paciente[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ConsultaApp.Paciente[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ConsultaApp.PacienteHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ConsultaApp.PacienteSeqHelper.id (), "PacienteSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ConsultaApp.Paciente[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ConsultaApp.Paciente value[] = null;
    int _len0 = istream.read_long ();
    value = new ConsultaApp.Paciente[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ConsultaApp.PacienteHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ConsultaApp.Paciente[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ConsultaApp.PacienteHelper.write (ostream, value[_i0]);
  }

}
